"""The README's "By the numbers" block, read from the repo and the ledger, never typed. Prints it; --write replaces
the block between the numbers markers in README.md.

  python -m wtdd.numbers            print
  python -m wtdd.numbers --write    write into README.md
"""
from __future__ import annotations
import json
import subprocess
import sys
from pathlib import Path

from .config import ROOT

START, END = "<!-- numbers:start -->", "<!-- numbers:end -->"


def count(pred) -> int:
    f = ROOT / "ledger.jsonl"
    return sum(1 for l in f.read_text().splitlines() if l.strip() and pred(l)) if f.exists() else 0


def block() -> str:
    tools = len([p for p in (ROOT / "wtdd" / "tools").glob("*.py") if p.name != "__init__.py"])
    files = subprocess.run(["git", "ls-files", "wtdd/*.py", "ui/index.html"], capture_output=True, text=True, cwd=ROOT).stdout.split()
    lines = sum(len((ROOT / f).read_text().splitlines()) for f in files)
    commits = len(subprocess.run(["git", "log", "--since=2026-09-13 00:00", "--oneline"], capture_output=True, text=True, cwd=ROOT).stdout.splitlines())
    ev = ROOT / "evals.json"
    rows = json.loads(ev.read_text())["rows"] if ev.exists() else []
    n = {
        "external apps, all live": 5,
        "tools, one file each": tools,
        "lines of Python and page": lines,
        "commits, build day": commits,
        "ledger rows, build day": count(lambda l: '"ts": "2026-09-13' in l),
        "light writes with read-back": count(lambda l: '"tool": "lights.set"' in l or '"tool": "lights.tuya_set"' in l),
        "dog commands with state read-back": count(lambda l: '"tool": "dog.cmd"' in l),
        "model calls (each a trace row)": count(lambda l: '"tool": "llm.generate"' in l),
        "posts to the group, each confirmed from chat.db": count(lambda l: '"tool": "chat.post"' in l and '"ok": true' in l),
        "eval trials, graded from device state": f"{len(rows)}, {sum(r['grade'] == 'pass' for r in rows)} pass, {sum(r['grade'] == 'unsafe' for r in rows)} unsafe",
    }
    out = ["| | |", "|---|---|"] + [f"| {k} | {v} |" for k, v in n.items()]
    return "\n".join(out) + "\n\n_Generated by `python -m wtdd.numbers --write` from the repo, `ledger.jsonl` and `evals.json`._"


def main(argv: list[str] | None = None) -> int:
    text = block()
    print(text)
    if "--write" in (argv or sys.argv[1:]):
        p = ROOT / "README.md"; s = p.read_text()
        if START not in s or END not in s:
            raise SystemExit(f"README.md has no {START} / {END} markers")
        p.write_text(s[: s.index(START) + len(START)] + "\n" + text + "\n" + s[s.index(END):])
    return 0


if __name__ == "__main__":
    sys.exit(main())
